// <auto-generated />
using System;
using EGovProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EGovProject.Migrations
{
    [DbContext(typeof(EgovernanceDB))]
    partial class EgovernanceDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EGovProject.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ContactDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("EGovProject.Models.Birth", b =>
                {
                    b.Property<int>("BirthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AppRelation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantFEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantFNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantLEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantLNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantMEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantMNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicantctzdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicantctzdistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicantctznum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicantvdcmu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicantward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BabyWeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthHelper")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthPlaceEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthPlaceNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Caste")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EDOBBSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EDOBBSM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EDOBBSY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FNameNepali")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherFEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherFNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherLEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherLNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherMEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherMNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fatherctzdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fatherctzdistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fatherctznum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fathervdcmu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fatherward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Formdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFFEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFFNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFLEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFLNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFMEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFMNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandiEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandiNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHandicapped")
                        .HasColumnType("bit");

                    b.Property<string>("LNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LNameNepali")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MNameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MNameNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarriageDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarriageRedNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherFEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherFNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherLEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherLNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherMEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherMNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motherctzdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motherctzdistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motherctznum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mothervdcmu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motherward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuVdc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NDOBBSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NDOBBSM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NDOBBSY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFNameNepali")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RLNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RLNameNepali")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RMNameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RMNameNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationDateEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationDateNepali")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ward")
                        .HasColumnType("int");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BirthId");

                    b.ToTable("Birth");
                });

            modelBuilder.Entity("EGovProject.Models.Complain", b =>
                {
                    b.Property<int>("ComplainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ComplainDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComplainId");

                    b.ToTable("Complains");
                });

            modelBuilder.Entity("EGovProject.Models.Death", b =>
                {
                    b.Property<int>("DeathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AppRelation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantFEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantFNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantLEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantLNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantMEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantMNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicantctzdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicantctzdistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicantctznum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicantvdcmu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicantward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Caste")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CitzNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DCtznNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DProvince")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DReport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DVDC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DWFullNameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DWFullNameNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DWard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dctzdistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeathDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeathDateReg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeathPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeathReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EDOBBSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EDOBBSM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EDOBBSY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FNameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FNameNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherFEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherFNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherLEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherLNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherMEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherMNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fatherctzdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fatherctzdistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fatherctznum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fathervdcmu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fatherward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Formdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFFEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFFNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFLEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFLNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFMEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFMNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdentityNo")
                        .HasColumnType("int");

                    b.Property<bool>("IsMarried")
                        .HasColumnType("bit");

                    b.Property<string>("IsVerified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LNameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LNameNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MNameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MNameNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherFEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherFNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherLEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherLNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherMEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherMNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motherctzdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motherctzdistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motherctznum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mothervdcmu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motherward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NDOBBSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NDOBBSM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NDOBBSY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFNameNepali")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RLNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RLNameNepali")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RMNameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RMNameNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationDateEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationDateNepali")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WNameFEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WNameFNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WNameMEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WNameMNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WNameSEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WNameSNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeathId");

                    b.ToTable("Deaths");
                });

            modelBuilder.Entity("EGovProject.Models.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Choose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("EGovProject.Models.Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProblemDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("EGovProject.Models.ViewModel.BirthModel", b =>
                {
                    b.Property<int>("BirthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AppRelation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantFEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantFNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantLEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantLNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantMEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantMNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicantctzdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicantctzdistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicantctznum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicantvdcmu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicantward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BabyWeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthHelper")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthPlaceEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthPlaceNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Caste")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EDOBBSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EDOBBSM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EDOBBSY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FNameNepali")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherFEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherFNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherLEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherLNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherMEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherMNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fatherctzdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fatherctzdistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fatherctznum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fathervdcmu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fatherward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Formdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFFEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFFNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFLEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFLNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFMEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFMNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandiEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandiNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHandicapped")
                        .HasColumnType("bit");

                    b.Property<string>("LNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LNameNepali")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MNameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MNameNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarriageDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarriageRedNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherFEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherFNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherLEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherLNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherMEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherMNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motherctzdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motherctzdistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motherctznum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mothervdcmu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motherward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuVdc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NDOBBSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NDOBBSM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NDOBBSY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFNameNepali")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RLNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RLNameNepali")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RMNameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RMNameNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationDateEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationDateNepali")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ward")
                        .HasColumnType("int");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BirthId");

                    b.ToTable("BirthModel");
                });

            modelBuilder.Entity("EGovProject.Models.ViewModel.ComplainModel", b =>
                {
                    b.Property<int>("ComplainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ComplainDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComplainId");

                    b.ToTable("ComplainModel");
                });

            modelBuilder.Entity("EGovProject.Models.ViewModel.ContactModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ContactDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactModel");
                });

            modelBuilder.Entity("EGovProject.Models.ViewModel.DeathModel", b =>
                {
                    b.Property<int>("DeathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AppRelation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantFEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantFNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantLEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantLNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantMEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantMNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicantctzdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicantctzdistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicantctznum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicantvdcmu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicantward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Caste")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CitzNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DCtznNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DProvince")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DReport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DVDC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DWFullNameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DWFullNameNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DWard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dctzdistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeathDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeathDateReg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeathPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeathReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EDOBBSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EDOBBSM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EDOBBSY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FNameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FNameNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherFEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherFNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherLEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherLNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherMEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherMNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fatherctzdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fatherctzdistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fatherctznum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fathervdcmu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fatherward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Formdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFFEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFFNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFLEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFLNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFMEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFMNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdentityNo")
                        .HasColumnType("int");

                    b.Property<bool>("IsMarried")
                        .HasColumnType("bit");

                    b.Property<string>("IsVerified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LNameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LNameNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MNameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MNameNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherFEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherFNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherLEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherLNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherMEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherMNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motherctzdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motherctzdistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motherctznum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mothervdcmu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motherward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NDOBBSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NDOBBSM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NDOBBSY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFNameNepali")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RLNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RLNameNepali")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RMNameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RMNameNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationDateEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationDateNepali")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WNameFEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WNameFNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WNameMEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WNameMNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WNameSEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WNameSNepali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeathId");

                    b.ToTable("DeathModel");
                });

            modelBuilder.Entity("EGovProject.Models.ViewModel.PollModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Choose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PollModel");
                });

            modelBuilder.Entity("EGovProject.Models.ViewModel.ProblemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProblemDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProblemModel");
                });
#pragma warning restore 612, 618
        }
    }
}
